configuration/configuration2.yaml:
  record_final_state: true
  final_success_state_code: q
  final_failure_state_code: q
  apps:
    vpn_app:
      package_name: com.wireguard.android
      apk_path: ./apk/wireguard.apk
  steps_order:
  - q
  steps:
    q:
      module: utilities.helpers.avd_utils
      function: delete_app_if_found
      description: q
      mandatory: true
      fail_strategy: ignore_failure
      pre_delay: 0.0
      post_delay: 0.0
      ascii_enabled: true
      record_state: true
      send_to_exchange: true
      start_state_code: q
      success_state_code: q
      failure_state_code: q
      params: {}
